cfg: !!python/object/apply:types.SimpleNamespace
  state:
    backbone: tf_efficientnetv2_s.in21k
    batch_size: 32
    exp_name: 20_crop-15e_noiseAug_CE_weighted_LS_pp_impulse2
    fmax: 22050.0
    fmin: 300
    hop_length: 1024
    impulse_prob: 0.2
    in_chans: 1
    lr: 0.000251
    n_classes: 66
    n_epochs: 20
    n_fft: 2048
    n_mels: 128
    power: 2
    pretrained: true
    sample_rate: 44100
    top_db: 80.0
    wav_crop_len: 15
    weight_decay: 0.0001
    window_size: 2048
optimizer_hparams:
  lr: 0.000251
  weight_decay: 0.0001
optimizer_name: Adam
