cfg: !!python/object/apply:types.SimpleNamespace
  state:
    backbone: tf_efficientnetv2_s.in21k
    batch_size: 32
    data_path: ../..//data/production_data/6s_crop/
    exp_name: lukas_tf_efficientnetv2_s.in21k_6s_crop_test1
    fmax: 30000
    fmin: 300
    hop_length: 2048
    impulse_prob: 0.2
    in_chans: 1
    include_val: true
    label_smoothing: 0.125
    lr: 0.001995262314968879
    max_amp: false
    max_noise: 0.06
    max_snr: 24
    mel_normalized: true
    min_snr: 4
    minmax_norm: false
    n_classes: 66
    n_epochs: 18
    n_fft: 4096
    n_mels: 128
    noise_prob: 0.2
    num_workers: 4
    power: 2
    pretrained: true
    sample_rate: 44100
    top_db: 80.0
    wav_crop_len: 6
    weight_decay: 5.0e-05
    window_size: 4096
optimizer_hparams:
  lr: 0.001995262314968879
  weight_decay: 5.0e-05
optimizer_name: Adam
