cfg: !!python/object/apply:types.SimpleNamespace
  state:
    backbone: tf_efficientnetv2_s.in21k
    fmax: 22050.0
    fmin: 300
    hop_length: 1024
    in_chans: 1
    lr: 0.0003
    n_classes: 66
    n_fft: 2048
    n_mels: 128
    power: 2
    pretrained: true
    sample_rate: 44100
    top_db: 80.0
    wav_crop_len: 15
    window_size: 2048
optimizer_hparams:
  lr: 0.0003
  weight_decay: 0.0001
optimizer_name: Adam
