cfg: !!python/object/apply:types.SimpleNamespace
  state:
    backbone: tf_efficientnetv2_s.in21k
    batch_size: 32
    data_path: ../..//data/production_data/6s_crop/
    exp_name: 1107_Mixup-True_SpecAug-True_valincFalse
    fmax: 22050.0
    fmin: 300
    hop_length: 1024
    impulse_prob: 0.25
    in_chans: 1
    include_val: false
    label_smoothing: 0.1
    lr: 0.0001
    max: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDgAAADk0NzU4ODYzMDk5MzkycQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTQ3
        NTg4NjMwOTkzOTJxAWEuAQAAAAAAAAArCFpC
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    max_amp: false
    max_noise: 0.05
    max_snr: 20
    mel_normalized: false
    min: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDgAAADk0NzU4ODYzMDk5NzI4cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTQ3
        NTg4NjMwOTk3MjhxAWEuAQAAAAAAAACSiL7C
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    min_snr: 5
    minmax_norm: true
    mixup: true
    mixup_prob: 1
    n_classes: 66
    n_epochs: 25
    n_fft: 2048
    n_mels: 128
    noise_prob: 0.25
    num_workers: 4
    power: 2
    pretrained: true
    sample_rate: 44100
    specaug: true
    specaug_prob: 0.25
    top_db: 80.0
    wav_crop_len: 6
    weight_decay: 0.0001
    window_size: 2048
optimizer_hparams:
  lr: 0.0001
  weight_decay: 0.0001
optimizer_name: Adam
