cfg: !!python/object/apply:types.SimpleNamespace
  state:
    backbone: tf_efficientnetv2_s.in21k
    batch_size: 32
    data_path: ../..//data/production_data/5s_crop/
    exp_name: lucas_mel_lr_amp_04
    fmax: 30000
    fmin: 400
    hop_length: 1024
    impulse_prob: 0.15
    in_chans: 1
    include_val: true
    label_smoothing: 0.1
    lr: 0.0017
    max_amp: false
    max_noise: 0.04
    max_snr: 20
    mel_normalized: true
    min_snr: 5
    minmax_norm: false
    n_classes: 66
    n_epochs: 18
    n_fft: 2048
    n_mels: 128
    noise_prob: 0.15
    num_workers: 4
    power: 2
    pretrained: true
    sample_rate: 44100
    top_db: 80.0
    wav_crop_len: 5
    weight_decay: 1.0e-05
    window_size: 2048
optimizer_hparams:
  lr: 0.0017
  weight_decay: 1.0e-05
optimizer_name: Adam
